---
# Setup infrastructure and application

- name: setup testing node
  hosts: postman-newman-dev
  remote_user: controller
  become: yes
  roles:
    - nodejs
  tasks:
    - name: install g++ which is required to install newman's dependencies
      apt: update_cache=yes pkg={{ item }} state=present cache_valid_time=3600
      with_items:
        - g++
    - name: install newman globally
      # Ideally we would do this using the NPM module - but it requires github.com/ansible/ansible-modules-extras/pull/876 to be merged
      command: npm install -g newman --unsafe-perm

- name: setup newman
  hosts: postman-newman-dev
  remote_user: app
  vars_files:
    - data/api-auth.yml
  tasks:
    - name: generate environment file
      template: src=templates/app/environment.json.j2 dest=/app/environment.json
