---
# Setup infrastructure and application

- name: setup testing node
  hosts: postman-newman-dev
  remote_user: controller
  become: yes
  roles:
    - nodejs
  tasks:
    - name: install newman npm package globally
      npm: name=newman global=yes

- name: setup newman
  hosts: postman-newman-dev
  remote_user: app
  vars_files:
    - data/api-auth.yml
  tasks:
    - name: generate environment file
      template: src=templates/app/environment.json.j2 dest=/app/environment.json
